language: python
python:
  - 2.7
  - 3.3
  - 3.4
env:
  - DJANGO=django==1.6.10
  - DJANGO=django==1.7.6
  - DJANGO=https://www.djangoproject.com/download/1.8b2/tarball/
install:
  - pip install $DJANGO
  - pip install PyOpenSSL
  - pip install requests
  - python setup.py -q install
script: python runtests.py
notifications:
  email: false